### ISSUE TITLE
chapmanu/ira redirect is closed source, returns 404

### ISSUE THREAD

**Issue by mileszim** [chapmanu/hummingbird#8]
Also want to point out I'm happy to be listed as maintainer for this. Ira, from what I remember, is duplicated (and likely at this point upgraded by you awesome people), but it contained secret keys checked into source, which is a defect of hummingbird resulting in a bad practice, and that is my bad. However, this project is open source, while Ira is private, so I'd recommend a distinction in your note that for your team developers, work on Ira, but this is not necessarily "abandoned". Also, if there have been made significant (or any changes) to ira from hummingbird, I'd love to merge those into here.

**Comment by tatwell** [comment]
Support notice has been updated.

I'm not sure what changes have been made in Ira. Ira is not a fork so issuing a pull request is not as simple as pushing a button. If you would like to see a PR, open a new issue and we'll address it when we have time.
